// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.11
// source: gRPC/interface.proto

package temp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// IncrementClient is the client API for Increment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IncrementClient interface {
	Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementReply, error)
}

type incrementClient struct {
	cc grpc.ClientConnInterface
}

func NewIncrementClient(cc grpc.ClientConnInterface) IncrementClient {
	return &incrementClient{cc}
}

func (c *incrementClient) Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementReply, error) {
	out := new(IncrementReply)
	err := c.cc.Invoke(ctx, "/temp.Increment/increment", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IncrementServer is the server API for Increment service.
// All implementations must embed UnimplementedIncrementServer
// for forward compatibility
type IncrementServer interface {
	Increment(context.Context, *IncrementRequest) (*IncrementReply, error)
	mustEmbedUnimplementedIncrementServer()
}

// UnimplementedIncrementServer must be embedded to have forward compatible implementations.
type UnimplementedIncrementServer struct {
}

func (UnimplementedIncrementServer) Increment(context.Context, *IncrementRequest) (*IncrementReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedIncrementServer) mustEmbedUnimplementedIncrementServer() {}

// UnsafeIncrementServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IncrementServer will
// result in compilation errors.
type UnsafeIncrementServer interface {
	mustEmbedUnimplementedIncrementServer()
}

func RegisterIncrementServer(s grpc.ServiceRegistrar, srv IncrementServer) {
	s.RegisterService(&Increment_ServiceDesc, srv)
}

func _Increment_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IncrementServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/temp.Increment/increment",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IncrementServer).Increment(ctx, req.(*IncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Increment_ServiceDesc is the grpc.ServiceDesc for Increment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Increment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "temp.Increment",
	HandlerType: (*IncrementServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "increment",
			Handler:    _Increment_Increment_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gRPC/interface.proto",
}
